"""extraction_runs + suggested_patient_id (T4.1)

Revision ID: 39f593f639da
Revises: c9d0e1f2a3b4
Create Date: 2026-07-14 20:20:02.810117

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39f593f639da"
down_revision: str | Sequence[str] | None = "c9d0e1f2a3b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="running", nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'error')", name=op.f("ck_extraction_runs_status_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["health_records.id"],
            name=op.f("fk_extraction_runs_record_id_health_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_runs")),
    )
    op.create_index(
        op.f("ix_extraction_runs_record_id"), "extraction_runs", ["record_id"], unique=False
    )
    op.add_column("health_records", sa.Column("suggested_patient_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_health_records_suggested_patient_id_family_members"),
        "health_records",
        "family_members",
        ["suggested_patient_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_health_records_suggested_patient_id_family_members"),
        "health_records",
        type_="foreignkey",
    )
    op.drop_column("health_records", "suggested_patient_id")
    op.drop_index(op.f("ix_extraction_runs_record_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    # ### end Alembic commands ###
