"""domain models: family, members, accounts, records, files

Revision ID: e6bc69637424
Revises:
Create Date: 2026-07-13 20:37:44.124506

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6bc69637424"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "families",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), server_default="Семья", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_families")),
    )
    op.create_table(
        "family_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.CheckConstraint("sex IN ('male', 'female')", name=op.f("ck_family_members_sex_allowed")),
        sa.ForeignKeyConstraint(
            ["family_id"], ["families.id"], name=op.f("fk_family_members_family_id_families")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_members")),
    )
    op.create_index(
        op.f("ix_family_members_family_id"), "family_members", ["family_id"], unique=False
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_member_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_member_id"],
            ["family_members.id"],
            name=op.f("fk_accounts_family_member_id_family_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("email", name=op.f("uq_accounts_email")),
        sa.UniqueConstraint("family_member_id", name=op.f("uq_accounts_family_member_id")),
    )
    op.create_table(
        "health_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_account_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("clinic", sa.String(), nullable=True),
        sa.Column("doctor", sa.String(), nullable=True),
        sa.Column("record_type", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_account_id"],
            ["accounts.id"],
            name=op.f("fk_health_records_author_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_account_id"],
            ["accounts.id"],
            name=op.f("fk_health_records_deleted_by_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["family_members.id"],
            name=op.f("fk_health_records_patient_id_family_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_records")),
    )
    op.create_index(
        op.f("ix_health_records_author_account_id"),
        "health_records",
        ["author_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_records_patient_id"), "health_records", ["patient_id"], unique=False
    )
    op.create_table(
        "record_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("stored_path", sa.String(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["health_records.id"],
            name=op.f("fk_record_files_record_id_health_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_record_files")),
        sa.UniqueConstraint("record_id", "position", name=op.f("uq_record_files_record_id")),
    )
    op.create_index(op.f("ix_record_files_record_id"), "record_files", ["record_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_record_files_record_id"), table_name="record_files")
    op.drop_table("record_files")
    op.drop_index(op.f("ix_health_records_patient_id"), table_name="health_records")
    op.drop_index(op.f("ix_health_records_author_account_id"), table_name="health_records")
    op.drop_table("health_records")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_family_members_family_id"), table_name="family_members")
    op.drop_table("family_members")
    op.drop_table("families")
    # ### end Alembic commands ###
